preDeploy:
  - apt-get update && apt-get install -y \
      libnss3 \
      libatk1.0-0 \
      libatk-bridge2.0-0 \
      libxcomposite1 \
      libxdamage1 \
      libxrandr2 \
      libgbm1 \
      libasound2 \
      libpangocairo-1.0-0 \
      libpango-1.0-0 \
      libcairo2 \
      libcups2 \
      libxkbcommon0 \
      libwayland-client0 \
      libwayland-cursor0 \
      libwayland-egl1
