services:
  - type: web
    name: my-scraper-app
    env: node
    branch: main
    repo: https://github.com/cryptotoked/my-scraper-app
    buildCommand: npm install && npx playwright install
    startCommand: npm start
    preDeploy:
      - apt-get update
      - apt-get install -y libgtk-4-1 libgraphene-1.0-0 libgstgl-1.0-0 libgstcodecparsers-1.0-0 libavif15 libenchant-2-2 libsecret-1-0 libmanette-0.2-0 libgles2
