services:
  - type: web
    name: my-scraper-app
    env: node
    branch: main
    plan: starter  # You can use the 'starter' plan for free
    buildCommand: npm install && npm run build  # Install dependencies and build the app
    startCommand: npm run start  # Start the Next.js app
    healthCheckPath: /api/scrape  # Ensure this endpoint exists and is working

