import type { Metadata } from "next";
import { Roboto, Poppins } from "next/font/google";
import "./globals.css";

// Importing Google Fonts with specified weights
const roboto = Roboto({
  weight: ['400', '700'], // Added valid font weights
  variable: "--font-roboto",
  subsets: ["latin"],
});

const poppins = Poppins({
  weight: ['400', '700'], // Added valid font weights
  variable: "--font-poppins",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${roboto.variable} ${poppins.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}

